set_property PACKAGE_PIN H15 [get_ports m_axi_error_0]
set_property PACKAGE_PIN L15 [get_ports m_axi_txn_done_0]
set_property IOSTANDARD LVCMOS33 [get_ports m_axi_error_0]
set_property IOSTANDARD LVCMOS33 [get_ports key]
set_property IOSTANDARD LVCMOS33 [get_ports m_axi_txn_done_0]
set_property PACKAGE_PIN L14 [get_ports key]
